version: '3.3'

services:
  tourism-scheduler-database:
    image: mysql:8.0.28
    restart: always
    environment:
      MYSQL_DATABASE: 'testdb2'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'mitoro1992'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    container_name: tourism-scheduler
