---
swagger: "2.0"
info:
  description: "This API is used to _________"
  version: "1.0.0"
  title: "CSCI 602 REST API"
  contact:
    name: "John Ravan"
    url: "https://theravans.com/"
    email: "ravanj1@citadel.edu"
  license:
    name: "MIT License"
    url: "https://www.mit.edu/"
host: "localhost:5000"
basePath: "/"
tags:
- name: "status-endpoints"
  description: "Status Endpoints"
paths:
  /defense:
    post:
      tags:
      - "status-endpoints"
      summary: "Adds defensive stats"
      operationId: "createDefenseUsingPOST"
      consumes:
      - "application/json"
      produces:
      - "*/*"
      parameters:
      - in: "body"
        name: "simpleObject"
        description: "Simple object"
        required: true
        schema:
          type: "object"
          additionalProperties:
            type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            type: "string"
        "201":
          description: "Created"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "The resource was not found"
        "422":
          description: "Cannot process request"
        "500":
          description: "Database error"
  /defense/firstName/{fname}/lastName/{lname}/position/{pos}:
    get:
      tags:
      - "status-endpoints"
      summary: "getdefense"
      operationId: "getdefenseUsingGET"
      produces:
      - "application/json"
      parameters:
      - name: "firstName"
        in: "path"
        description: "firstName"
        required: true
        type: "string"
      - name: "lastName"
        in: "path"
        description: "lastName"
        required: true
        type: "string"
      - name: "position"
        in: "path"
        description: "position"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            type: "string"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
  /health:
    get:
      tags:
      - "status-endpoints"
      summary: "health"
      operationId: "healthUsingGET"
      produces:
      - "application/json"
      responses:
        "200":
          description: "OK"
          schema:
            type: "string"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
  /info:
    get:
      tags:
      - "status-endpoints"
      summary: "info"
      operationId: "infoUsingGET"
      produces:
      - "application/json"
      responses:
        "200":
          description: "OK"
          schema:
            type: "string"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
  /passing:
    post:
      tags:
      - "status-endpoints"
      summary: "Adds passing stats"
      operationId: "createPassingUsingPOST"
      consumes:
      - "application/json"
      produces:
      - "*/*"
      parameters:
      - in: "body"
        name: "simpleObject"
        description: "Simple object"
        required: true
        schema:
          type: "object"
          additionalProperties:
            type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            type: "string"
        "201":
          description: "Created"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "The resource was not found"
        "422":
          description: "Cannot process request"
        "500":
          description: "Database error"
  /passing/firstName/{firstName}/lastName/{lastName}/position/{position}:
    get:
      tags:
      - "status-endpoints"
      summary: "getPassing"
      operationId: "getPassingUsingGET"
      produces:
      - "application/json"
      parameters:
      - name: "firstName"
        in: "path"
        description: "firstName"
        required: true
        type: "string"
      - name: "lastName"
        in: "path"
        description: "lastName"
        required: true
        type: "string"
      - name: "position"
        in: "path"
        description: "position"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            type: "string"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
  /person:
    post:
      tags:
      - "status-endpoints"
      summary: "Creates a person object"
      operationId: "createAPersonUsingPOST"
      consumes:
      - "application/json"
      produces:
      - "*/*"
      parameters:
      - in: "body"
        name: "simpleObject"
        description: "Simple object"
        required: true
        schema:
          type: "object"
          additionalProperties:
            type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            type: "string"
        "201":
          description: "Created"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "The resource was not found"
        "422":
          description: "Cannot process request"
  /person/{id}:
    get:
      tags:
      - "status-endpoints"
      summary: "getPerson"
      operationId: "getPersonUsingGET"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "id"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            type: "string"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
  /place:
    get:
      tags:
      - "status-endpoints"
      summary: "getAllPlaces"
      operationId: "getAllPlacesUsingGET"
      produces:
      - "application/json"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Iterable«Place»"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
  /place/search:
    get:
      tags:
      - "status-endpoints"
      summary: "search"
      operationId: "searchUsingGET"
      produces:
      - "application/json"
      parameters:
      - name: "subtype"
        in: "query"
        description: "subtype"
        required: true
        type: "string"
      - name: "type"
        in: "query"
        description: "type"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Place"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
  /place/search2:
    get:
      tags:
      - "status-endpoints"
      summary: "search"
      operationId: "searchUsingGET_1"
      produces:
      - "application/json"
      parameters:
      - name: "type"
        in: "query"
        description: "type"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Place"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
  /place/{id}:
    get:
      tags:
      - "status-endpoints"
      summary: "getPlace"
      operationId: "getPlaceUsingGET"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "id"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            type: "string"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
  /player/firstName/{firstName}/lastName/{lastName}/position/{position}:
    get:
      tags:
      - "status-endpoints"
      summary: "getPlayer"
      operationId: "getPlayerUsingGET"
      produces:
      - "application/json"
      parameters:
      - name: "firstName"
        in: "path"
        description: "firstName"
        required: true
        type: "string"
      - name: "lastName"
        in: "path"
        description: "lastName"
        required: true
        type: "string"
      - name: "position"
        in: "path"
        description: "position"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            type: "string"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
  /players:
    post:
      tags:
      - "status-endpoints"
      summary: "Adds a player to the database"
      operationId: "createAPlayerUsingPOST"
      consumes:
      - "application/json"
      produces:
      - "*/*"
      parameters:
      - in: "body"
        name: "simpleObject"
        description: "Simple object"
        required: true
        schema:
          type: "object"
          additionalProperties:
            type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            type: "string"
        "201":
          description: "Created"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "The resource was not found"
        "422":
          description: "Cannot process request"
        "500":
          description: "Database error"
  /receiving:
    post:
      tags:
      - "status-endpoints"
      summary: "Adds receiving stats"
      operationId: "createReceivingUsingPOST"
      consumes:
      - "application/json"
      produces:
      - "*/*"
      parameters:
      - in: "body"
        name: "simpleObject"
        description: "Simple object"
        required: true
        schema:
          type: "object"
          additionalProperties:
            type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            type: "string"
        "201":
          description: "Created"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "The resource was not found"
        "422":
          description: "Cannot process request"
        "500":
          description: "Database error"
  /receiving/firstName/{firstName}/lastName/{lastName}/position/{position}:
    get:
      tags:
      - "status-endpoints"
      summary: "getreceiving"
      operationId: "getreceivingUsingGET"
      produces:
      - "application/json"
      parameters:
      - name: "firstName"
        in: "path"
        description: "firstName"
        required: true
        type: "string"
      - name: "lastName"
        in: "path"
        description: "lastName"
        required: true
        type: "string"
      - name: "position"
        in: "path"
        description: "position"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            type: "string"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
  /rushing:
    post:
      tags:
      - "status-endpoints"
      summary: "Adds rushing stats"
      operationId: "createRushingUsingPOST"
      consumes:
      - "application/json"
      produces:
      - "*/*"
      parameters:
      - in: "body"
        name: "simpleObject"
        description: "Simple object"
        required: true
        schema:
          type: "object"
          additionalProperties:
            type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            type: "string"
        "201":
          description: "Created"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "The resource was not found"
        "422":
          description: "Cannot process request"
        "500":
          description: "Database error"
  /rushing/firstName/{firstName}/lastName/{lastName}/position/{position}:
    get:
      tags:
      - "status-endpoints"
      summary: "getRushing"
      operationId: "getRushingUsingGET"
      produces:
      - "application/json"
      parameters:
      - name: "firstName"
        in: "path"
        description: "firstName"
        required: true
        type: "string"
      - name: "lastName"
        in: "path"
        description: "lastName"
        required: true
        type: "string"
      - name: "position"
        in: "path"
        description: "position"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            type: "string"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
  /whatsapp/send:
    post:
      tags:
      - "status-endpoints"
      summary: "Sends data to Whatsapp via Twillio"
      operationId: "sendViaWhatsappUsingPOST"
      consumes:
      - "application/json"
      produces:
      - "*/*"
      parameters:
      - in: "body"
        name: "simpleObject"
        description: "Simple object"
        required: true
        schema:
          type: "object"
          additionalProperties:
            type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Message"
        "201":
          description: "Created"
        "400":
          description: "Bad Request"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "The resource was not found"
        "422":
          description: "Cannot process request"
definitions:
  Iterable«Place»:
    type: "object"
    title: "Iterable«Place»"
  Message:
    type: "object"
    properties:
      accountSid:
        type: "string"
      apiVersion:
        type: "string"
      body:
        type: "string"
      dateCreated:
        type: "string"
        format: "date-time"
      dateSent:
        type: "string"
        format: "date-time"
      dateUpdated:
        type: "string"
        format: "date-time"
      direction:
        type: "string"
        enum:
        - "INBOUND"
        - "OUTBOUND_API"
        - "OUTBOUND_CALL"
        - "OUTBOUND_REPLY"
      errorCode:
        type: "integer"
        format: "int32"
      errorMessage:
        type: "string"
      from:
        $ref: "#/definitions/PhoneNumber"
      messagingServiceSid:
        type: "string"
      numMedia:
        type: "string"
      numSegments:
        type: "string"
      price:
        type: "string"
      priceUnit:
        type: "number"
      sid:
        type: "string"
      status:
        type: "string"
        enum:
        - "ACCEPTED"
        - "CANCELED"
        - "DELIVERED"
        - "FAILED"
        - "PARTIALLY_DELIVERED"
        - "QUEUED"
        - "READ"
        - "RECEIVED"
        - "RECEIVING"
        - "SCHEDULED"
        - "SENDING"
        - "SENT"
        - "UNDELIVERED"
      subresourceUris:
        type: "object"
        additionalProperties:
          type: "string"
      to:
        type: "string"
      uri:
        type: "string"
    title: "Message"
  PhoneNumber:
    type: "object"
    properties:
      endpoint:
        type: "string"
    title: "PhoneNumber"
  Place:
    type: "object"
    properties:
      address:
        type: "string"
      averageTime:
        type: "string"
      fridayHours:
        type: "string"
      id:
        type: "integer"
        format: "int32"
      mondayHours:
        type: "string"
      name:
        type: "string"
      numOfReviews:
        type: "integer"
        format: "int32"
      priceLevel:
        type: "string"
      rating:
        type: "number"
        format: "float"
      saturdayHours:
        type: "string"
      subType:
        type: "string"
      subType2:
        type: "string"
      subType3:
        type: "string"
      sundayHours:
        type: "string"
      thursdayHours:
        type: "string"
      tuesdayHours:
        type: "string"
      type:
        type: "string"
      wednesdayHours:
        type: "string"
    title: "Place"
